// <auto-generated />
namespace ServiceMadeEasy.In.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class acolumdatatypechange : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(acolumdatatypechange));
        
        string IMigrationMetadata.Id
        {
            get { return "201902250337190_acolumdatatypechange"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
